Issue-2-user-can-view-their-entries | Richard Watanabe
Richard-Watanabe/code-journal pull request #6
Opened 2021-07-14 18:04 UTC by Richard-Watanabe

https://user-images.githubusercontent.com/85139853/125670795-589cd08c-851d-45b7-a270-2d04f0c7c410.mp4

2021-07-14 18:11 UTC, codingcodymiller requested changes

2021-07-14 18:11 UTC, codingcodymiller commented on js/main.js
> +  window.location.reload();
Oh nooooo 😱 

`location.reload()` should never be used, this reloads your page entirely, literally the most inefficient action you could take. If this is to make the new entry show up when you navigate to the entries view, the real answer is to generate a DOM tree for that entry in your `submit` event handler, then `prepend` that entry to the entries list before changing views. You will get the same effect without needing to reload the entire page..

2021-07-14 18:11 UTC, codingcodymiller commented on js/main.js
> +if (data.nextEntryId > 1) {
This condition would be better off checking if `data.entries` is empty, you shouldn't use ids as a count.

2021-07-14 18:11 UTC, codingcodymiller commented on js/main.js
> +}
You would likely benefit from making one function named something like `switchView` that receives the name of a view as an argument, then shows that view and hides all other views.

2021-07-14 21:38 UTC, Richard-Watanabe commented
https://user-images.githubusercontent.com/85139853/125696523-3ce6d010-30e0-43f4-85cc-b06240703bb7.mp4

2021-07-14 21:50 UTC, codingcodymiller requested changes

2021-07-14 21:50 UTC, codingcodymiller commented on js/main.js
> +}
You should switch this to a function that takes the name of a view as an argument, then shows that view and hides all other views. That way you don't need to add a new conditional block here for every view you create. I recommend going back to `javascript-view-swapping` for a refresher on how to accomplish this.

2021-07-14 21:50 UTC, codingcodymiller commented on js/main.js
> +  $noEntry.className = 'hidden';
You should handle this with your `switchView` function once you change it to accept an argument of the name of the view to show

2021-07-15 17:52 UTC, Richard-Watanabe commented
https://user-images.githubusercontent.com/85139853/125834400-24e19653-4f8e-49b6-9720-0e148a000ad9.mp4

2021-07-15 17:59 UTC, codingcodymiller requested changes

2021-07-15 17:59 UTC, codingcodymiller commented on js/main.js
> +  switchView(data.view);
this can likely be removed

2021-07-15 17:59 UTC, codingcodymiller commented on js/main.js
> +    }
You can just save the value of `event.target.getAttribute('data-view')` into a variable and pass that as an argument to `switchView`, which should avoid the need to have a conditional here

2021-07-15 18:08 UTC, Richard-Watanabe commented
https://user-images.githubusercontent.com/85139853/125836464-d2a55042-d0e3-46fc-aa19-0d18d10bef88.mp4

2021-07-15 18:10 UTC, codingcodymiller approved these changes

2021-07-15 18:11 UTC, merged